import 'package:flutter/material.dart';

class TermsConditionsScreen extends StatelessWidget {
  const TermsConditionsScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Terms & Conditions'),
        centerTitle: true,
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(16.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(
              'Terms and Conditions',
              style: Theme.of(context).textTheme.headlineMedium?.copyWith(
                fontWeight: FontWeight.bold,
                color: Theme.of(context).colorScheme.primary,
              ),
            ),
            const SizedBox(height: 8),
            Text(
              'Last updated: Nov 2025',
              style: Theme.of(context).textTheme.bodySmall?.copyWith(
                color: Colors.grey[600],
              ),
            ),
            const SizedBox(height: 24),
            
            _buildSection(
              context,
              'Acceptance of Terms',
              'By accessing and using AI Math Solver, you accept and agree to be bound by the terms and provision of this agreement. If you do not agree to abide by the above, please do not use this service.',
            ),
            
            _buildSection(
              context,
              'Use License',
              'Permission is granted to temporarily download one copy of AI Math Solver for personal, non-commercial transitory viewing only. This is the grant of a license, not a transfer of title, and under this license you may not:\n\n• Modify or copy the materials\n• Use the materials for any commercial purpose\n• Attempt to reverse engineer any software contained in the app\n• Remove any copyright or other proprietary notations',
            ),
            
            _buildSection(
              context,
              'Educational Purpose',
              'AI Math Solver is designed to assist with mathematical learning and problem-solving. Users should use this tool as a learning aid and are encouraged to understand the solutions provided rather than simply copying answers.',
            ),
            
            _buildSection(
              context,
              'AI-Generated Content',
              'The mathematical solutions and explanations provided by AI Math Solver are generated by artificial intelligence. While we strive for accuracy, users should verify important calculations and consult with qualified educators or professionals for critical academic or professional work.',
            ),
            
            _buildSection(
              context,
              'User Responsibilities',
              'Users are responsible for:\n\n• Using the app in accordance with applicable laws and regulations\n• Not uploading inappropriate, offensive, or copyrighted content\n• Respecting intellectual property rights\n• Not attempting to circumvent security measures',
            ),
            
            _buildSection(
              context,
              'Disclaimer',
              'The information on AI Math Solver is provided on an "as is" basis. To the fullest extent permitted by law, this company excludes all representations, warranties, conditions and terms related to our app and the use of this app.',
            ),
            
            _buildSection(
              context,
              'Limitations',
              'In no event shall AI Math Solver or its suppliers be liable for any damages (including, without limitation, damages for loss of data or profit, or due to business interruption) arising out of the use or inability to use the app.',
            ),
            
            _buildSection(
              context,
              'Modifications',
              'AI Math Solver may revise these terms of service at any time without notice. By using this app, you are agreeing to be bound by the then current version of these terms of service.',
            ),
            
            _buildSection(
              context,
              'Contact Information',
              'If you have any questions about these Terms and Conditions, please contact us through the app or visit our support page.',
            ),
            
            const SizedBox(height: 32),
            
            Center(
              child: ElevatedButton(
                onPressed: () => Navigator.pop(context),
                child: const Text('I Understand'),
              ),
            ),
            
            const SizedBox(height: 16),
          ],
        ),
      ),
    );
  }

  Widget _buildSection(BuildContext context, String title, String content) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 20),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            title,
            style: Theme.of(context).textTheme.titleLarge?.copyWith(
              fontWeight: FontWeight.w600,
              color: Theme.of(context).colorScheme.primary,
            ),
          ),
          const SizedBox(height: 8),
          Text(
            content,
            style: Theme.of(context).textTheme.bodyMedium?.copyWith(
              height: 1.5,
            ),
          ),
        ],
      ),
    );
  }
}